name = "qq-music-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "qq-music-api"
database_id = "746057bd-777c-4b41-927c-0dd4a1b50b31" 

# 定时刷新凭证 (每天凌晨 3 点)
[triggers]
crons = ["0 3 * * *"]


# 开启日志
[observability]
[observability.logs]
enabled = true
invocation_logs = true
